version: "3"
services:
  database:
    image: mdillon/postgis
    container_name: inventory-db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway:6.3.2
    container_name: flyway-migration
    environment:
      FLYWAY_URL: jdbc:postgresql://database/${PGDATABASE}
      FLYWAY_USER: ${PGUSER}
      FLYWAY_PASSWORD: ${PGPASSWORD}
    command: -connectRetries=60 migrate
    volumes:
      - ./db:/flyway/sql
    depends_on:
      - database
  be-server:
    build: ./packages/backend/.
    container_name: hospital-inventory-tracker-BE-server
    environment:
      NODE_ENV: ${NODE_ENV}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGLOGGING: 
      PORT: ${PORT}
      DEBUG: ${DEBUG}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - node_modules:/node_modules
    depends_on:
      - flyway
    networks:
      - intra
  fe-server:
    build: 
      context: ./packages/frontend/.
      dockerfile: Dockerfile.${NODE_ENV}
    container_name: 'hospital-inventory-tracker-FE-server'
    environment:
      BE_PORT: ${PORT}
    ports:
      - 80:80
      - 8080:8080
    networks:
      - intra
volumes:
  node_modules:
networks:
  intra: